### ISSUE TITLE
New boost releases?

### ISSUE THREAD

**Issue by vinipsmaker2** [ned14/boost-release#2]

**Comment by ned14** [comment]
I stopped using Boost personally, so I never resurrected the daemon which updated this after a server upgrade.

Were you actually using this?

**Comment by vinipsmaker** [comment]
Yes, I was using this, but I can migrate within 10min.

Just put a warning on the front page then and we are good.

**Comment by ned14** [comment]
Oh ok, sorry about the inconvenience then. I had assumed lack of forks meant nobody was using it.
